name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        

    steps:
      - uses: aabadie/action-install-python-requirements@v2.0.1
        with:
          requirements: requirements.txt
          update-pip: true
        
      - run: pytest flask_testing
      - run: mypy .
      - run: black --diff --check .
      - run: flake8 .
      - run: isort .

      

