name: Run Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
        
    steps:
  # this Action should follow steps to set up Python build environment
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v4
      
    - run: pytest flask_testing
    - run: mypy .
    - run: black --diff --check .
    - run: flake8 .
    - run: isort .

      

